In [1]:
import pandas as pd

In [5]:
rst1 = pd.read_csv(r'C:\works\dacon\img_clf\data\result.csv')
rst2 = pd.read_csv(r'C:\works\dacon\img_clf\data\result\result.csv')

In [6]:
rst1

          image_path  prediction
0     TEST_00000.jpg         253
1     TEST_00001.jpg         353
2     TEST_00002.jpg         146
3     TEST_00003.jpg         185
4     TEST_00004.jpg          22
...              ...         ...
8253  TEST_08253.jpg         377
8254  TEST_08254.jpg         190
8255  TEST_08255.jpg          84
8256  TEST_08256.jpg         246
8257  TEST_08257.jpg         264

[8258 rows x 2 columns]

In [7]:
rst2

          image_path  prediction
0     TEST_00000.jpg         253
1     TEST_00001.jpg         353
2     TEST_00002.jpg         146
3     TEST_00003.jpg         185
4     TEST_00004.jpg          22
...              ...         ...
8253  TEST_08253.jpg         377
8254  TEST_08254.jpg         190
8255  TEST_08255.jpg          84
8256  TEST_08256.jpg         246
8257  TEST_08257.jpg         264

[8258 rows x 2 columns]

In [8]:
rst2['check'] = rst2['prediction'] == rst1['prediction']

In [10]:
rst2['check'].value_counts()

check
True     7798
False     460
Name: count, dtype: int64

In [22]:
train_df = pd.read_csv(r'C:\works\dacon\img_clf\data\train_csv\train_file_list.csv')
label_dict = train_df[['folder_name', 'label']].drop_duplicates().set_index('label').to_dict()['folder_name']
rst2['label'] = rst2['prediction'].map(lambda x: label_dict.get(x, 'unknown'))
sample_df = pd.read_csv(r'C:\works\dacon\img_clf\data\sample_submission.csv')

In [23]:
rst2.to_csv(r'../data/result/result_mapped.csv', index=False)

In [24]:
# Prepare empty DataFrame with same columns as sample_df
submission_df = pd.DataFrame(0, index=range(len(rst2)), columns=sample_df.columns)

# Assign ID from image_path (remove extension)
submission_df["ID"] = rst2["image_path"].str.replace(".jpg", "", regex=False)

# For each row, set the corresponding label column to 1
for idx, label in enumerate(rst2["label"]):
    if label in submission_df.columns:
        submission_df.at[idx, label] = 1

In [30]:
submission_df.to_csv(r'../data/result/submission2.csv', index=False)